from app.repositories.user import user_repository
from app.repositories.role_verification import role_verification_repository
from app.repositories.offer import offer_repository
from app.repositories.stock import stock_repository
from app.repositories.product import product_repository
from app.repositories.address import address_repository
from app.repositories.cart import cart_repository
from app.repositories.order import order_repository
from app.repositories.payment import payment_repository
from app.repositories.review import review_repository
