"""complete prototype backend schema

Revision ID: b1f9cea001f6
Revises: 001_initial_schema
Create Date: 2026-07-14 01:01:05.605468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1f9cea001f6'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'menunggu_pembayaran' BEFORE 'diproses'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'refund_pending'")
    op.execute("ALTER TYPE payment_status_enum ADD VALUE IF NOT EXISTS 'refund_failed'")
    postgresql.ENUM('buyer_order', 'farmer_offer', name='payment_purpose_enum').create(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM('pending_payment', 'active', 'depleted', name='stock_status_enum').create(
        op.get_bind(), checkfirst=True
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_reference_id'), 'ledger_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_reference_type'), 'ledger_transactions', ['reference_type'], unique=False)
    op.create_table('market_price_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('commodity', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=150), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('volume_kg', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observed_at', 'commodity', 'district', 'source', name='uq_price_observation')
    )
    op.create_index(op.f('ix_market_price_observations_commodity'), 'market_price_observations', ['commodity'], unique=False)
    op.create_index(op.f('ix_market_price_observations_district'), 'market_price_observations', ['district'], unique=False)
    op.create_index(op.f('ix_market_price_observations_observed_at'), 'market_price_observations', ['observed_at'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('artifact_path', sa.String(length=1000), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_table('price_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('commodity', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=150), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_for', sa.Date(), nullable=False),
    sa.Column('predicted_price_per_kg', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('upper_bound', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_predictions_commodity'), 'price_predictions', ['commodity'], unique=False)
    op.create_index(op.f('ix_price_predictions_district'), 'price_predictions', ['district'], unique=False)
    op.create_index(op.f('ix_price_predictions_model_version'), 'price_predictions', ['model_version'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='training_status_enum'), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_status'), 'training_runs', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('checkout_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'cancelled', name='checkout_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_checkout_groups_buyer_id'), 'checkout_groups', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_checkout_groups_status'), 'checkout_groups', ['status'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_code'), 'ledger_entries', ['account_code'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkout_group_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'committed', 'released', name='reservation_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_group_id'], ['checkout_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_group_id', 'product_id', name='uq_reservation_checkout_product')
    )
    op.create_index(op.f('ix_inventory_reservations_checkout_group_id'), 'inventory_reservations', ['checkout_group_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_product_id'), 'inventory_reservations', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_status'), 'inventory_reservations', ['status'], unique=False)
    op.create_table('product_stock_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'stock_id', name='uq_product_stock_allocation')
    )
    op.create_index(op.f('ix_product_stock_allocations_product_id'), 'product_stock_allocations', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_stock_allocations_stock_id'), 'product_stock_allocations', ['stock_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('opened_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'rejected', name='dispute_status_enum'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('refund_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_opened_by_id'), 'disputes', ['opened_by_id'], unique=False)
    op.create_index(op.f('ix_disputes_order_id'), 'disputes', ['order_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_photo', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('rate_id', sa.String(length=255), nullable=False),
    sa.Column('courier', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('awb', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'booked', 'picked_up', 'in_transit', 'delivered', 'cancelled', 'failed', name='shipment_status_enum'), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('awb'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('provider_order_id')
    )
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('dispute_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_comments_dispute_id'), 'dispute_comments', ['dispute_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='attempt_status_enum'), nullable=False),
    sa.Column('snap_token', sa.String(length=500), nullable=True),
    sa.Column('redirect_url', sa.String(length=1000), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id'),
    sa.UniqueConstraint('external_transaction_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payment_attempts_payment_id'), 'payment_attempts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payout_status_enum'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_index(op.f('ix_payouts_user_id'), 'payouts', ['user_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'booked', 'picked_up', 'in_transit', 'delivered', 'cancelled', 'failed', name='shipment_status_enum', create_type=False), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'provider_event_id', name='uq_shipment_provider_event')
    )
    op.create_index(op.f('ix_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.add_column('addresses', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('addresses', sa.Column('district', sa.String(length=150), nullable=True))
    op.add_column('addresses', sa.Column('city', sa.String(length=150), nullable=True))
    op.add_column('addresses', sa.Column('province', sa.String(length=150), nullable=True))
    op.add_column('addresses', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('addresses', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('offers', sa.Column('distributor_id', sa.UUID(), nullable=True))
    op.add_column('offers', sa.Column('quantity_kg', sa.Numeric(precision=14, scale=2), nullable=True))
    op.execute("UPDATE offers SET quantity_kg = CASE WHEN unit::text = 'ton' THEN quantity * 1000 ELSE quantity END")
    op.alter_column('offers', 'quantity_kg', nullable=False)
    op.create_index(op.f('ix_offers_distributor_id'), 'offers', ['distributor_id'], unique=False)
    op.create_foreign_key('fk_offers_distributor_id', 'offers', 'users', ['distributor_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('checkout_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_orders_checkout_group_id'), 'orders', ['checkout_group_id'], unique=False)
    op.create_foreign_key('fk_orders_checkout_group_id', 'orders', 'checkout_groups', ['checkout_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('offer_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('checkout_group_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('payer_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('payee_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('purpose', postgresql.ENUM('buyer_order', 'farmer_offer', name='payment_purpose_enum', create_type=False), nullable=True))
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.execute("""UPDATE payments p SET payer_id=o.buyer_id, payee_id=o.distributor_id,
               purpose='buyer_order', idempotency_key=p.midtrans_order_id
               FROM orders o WHERE p.order_id=o.id""")
    op.alter_column('payments', 'payer_id', nullable=False)
    op.alter_column('payments', 'purpose', nullable=False)
    op.alter_column('payments', 'idempotency_key', nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payments_checkout_group_id'), 'payments', ['checkout_group_id'], unique=False)
    op.create_unique_constraint('uq_payments_offer_id', 'payments', ['offer_id'])
    op.create_unique_constraint('uq_payments_idempotency_key', 'payments', ['idempotency_key'])
    op.create_foreign_key('fk_payments_offer_id', 'payments', 'offers', ['offer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_payments_checkout_group_id', 'payments', 'checkout_groups', ['checkout_group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_payments_payee_id', 'payments', 'users', ['payee_id'], ['id'])
    op.create_foreign_key('fk_payments_payer_id', 'payments', 'users', ['payer_id'], ['id'])
    op.add_column('products', sa.Column('stock_reserved', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('unit', sa.String(length=10), nullable=False, server_default='kg'))
    op.alter_column('products', 'stock_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('role_verifications', sa.Column('consent_given', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('role_verifications', sa.Column('consent_version', sa.String(length=30), nullable=False, server_default='v1'))
    op.add_column('role_verifications', sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('role_verifications', 'ktp_number', existing_type=sa.String(length=50), type_=sa.String(length=500), existing_nullable=False)
    op.add_column('stock', sa.Column('quantity_reserved', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('stock', sa.Column('unit', sa.String(length=10), nullable=False, server_default='kg'))
    op.add_column('stock', sa.Column('status', postgresql.ENUM('pending_payment', 'active', 'depleted', name='stock_status_enum', create_type=False), nullable=False, server_default='active'))
    op.create_index(op.f('ix_stock_status'), 'stock', ['status'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_stock_status'), table_name='stock')
    op.drop_column('stock', 'status')
    op.drop_column('stock', 'unit')
    op.drop_column('stock', 'quantity_reserved')
    op.drop_column('role_verifications', 'consent_at')
    op.alter_column('role_verifications', 'ktp_number', existing_type=sa.String(length=500), type_=sa.String(length=50), existing_nullable=False)
    op.drop_column('role_verifications', 'consent_version')
    op.drop_column('role_verifications', 'consent_given')
    op.alter_column('products', 'stock_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('products', 'unit')
    op.drop_column('products', 'stock_reserved')
    op.drop_constraint('fk_payments_payer_id', 'payments', type_='foreignkey')
    op.drop_constraint('fk_payments_payee_id', 'payments', type_='foreignkey')
    op.drop_constraint('fk_payments_checkout_group_id', 'payments', type_='foreignkey')
    op.drop_constraint('fk_payments_offer_id', 'payments', type_='foreignkey')
    op.drop_constraint('uq_payments_idempotency_key', 'payments', type_='unique')
    op.drop_constraint('uq_payments_offer_id', 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_checkout_group_id'), table_name='payments')
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('payments', 'idempotency_key')
    op.drop_column('payments', 'purpose')
    op.drop_column('payments', 'payee_id')
    op.drop_column('payments', 'payer_id')
    op.drop_column('payments', 'checkout_group_id')
    op.drop_column('payments', 'offer_id')
    op.drop_constraint('fk_orders_checkout_group_id', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_checkout_group_id'), table_name='orders')
    op.drop_column('orders', 'checkout_group_id')
    op.drop_constraint('fk_offers_distributor_id', 'offers', type_='foreignkey')
    op.drop_index(op.f('ix_offers_distributor_id'), table_name='offers')
    op.drop_column('offers', 'quantity_kg')
    op.drop_column('offers', 'distributor_id')
    op.drop_column('addresses', 'longitude')
    op.drop_column('addresses', 'latitude')
    op.drop_column('addresses', 'province')
    op.drop_column('addresses', 'city')
    op.drop_column('addresses', 'district')
    op.drop_column('addresses', 'postal_code')
    op.drop_index(op.f('ix_shipment_events_shipment_id'), table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_payouts_user_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_payment_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_dispute_comments_dispute_id'), table_name='dispute_comments')
    op.drop_table('dispute_comments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_order_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_opened_by_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_product_stock_allocations_stock_id'), table_name='product_stock_allocations')
    op.drop_index(op.f('ix_product_stock_allocations_product_id'), table_name='product_stock_allocations')
    op.drop_table('product_stock_allocations')
    op.drop_index(op.f('ix_inventory_reservations_status'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_product_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_checkout_group_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_code'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_checkout_groups_status'), table_name='checkout_groups')
    op.drop_index(op.f('ix_checkout_groups_buyer_id'), table_name='checkout_groups')
    op.drop_table('checkout_groups')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_training_runs_status'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_price_predictions_model_version'), table_name='price_predictions')
    op.drop_index(op.f('ix_price_predictions_district'), table_name='price_predictions')
    op.drop_index(op.f('ix_price_predictions_commodity'), table_name='price_predictions')
    op.drop_table('price_predictions')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_market_price_observations_observed_at'), table_name='market_price_observations')
    op.drop_index(op.f('ix_market_price_observations_district'), table_name='market_price_observations')
    op.drop_index(op.f('ix_market_price_observations_commodity'), table_name='market_price_observations')
    op.drop_table('market_price_observations')
    op.drop_index(op.f('ix_ledger_transactions_reference_type'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_reference_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    for enum_name in (
        'training_status_enum', 'checkout_status_enum', 'reservation_status_enum',
        'dispute_status_enum', 'shipment_status_enum', 'attempt_status_enum',
        'payout_status_enum', 'payment_purpose_enum', 'stock_status_enum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
